version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Update Autotask
          command: |
            npm install defender-autotask-client
            defender-autotask update-code $API_SECRET <check first>
            defender-autotask update-code $API_SECRET <check first> 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: OpenQ
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^staging.*/